<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2020-11-06T11:30:02" tests="0" file="cypress/integration/genericError.feature" failures="0" time="0">
  </testsuite>
  <testsuite name="Generic Error" timestamp="2020-11-06T11:30:02" tests="1" failures="1" time="0">
    <testcase name="Generic Error Show show the generic error when trying to create an invalid basket" time="0" classname="Show show the generic error when trying to create an invalid basket">
      <failure message="`cy.setCookie()` must be passed two string arguments for `name` and `value`.

https://on.cypress.io/setcookie" type="CypressError"><![CDATA[CypressError: `cy.setCookie()` must be passed two string arguments for `name` and `value`.

https://on.cypress.io/setcookie
    at Context.setCookie (http://localhost:61640/__cypress/runner/cypress_runner.js:156649:19)
From Your Spec Code:
    at setCookie (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:324:13)
    at _callee$ (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:60:20)
    at tryCatch (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:40090:40)
    at Generator.invoke [as _invoke] (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:40319:22)
    at Generator.prototype.<computed> [as next] (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:40142:21)
    at asyncGeneratorStep (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:401:24)
    at _next (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:423:9)
    at eval (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:430:7)
at new Promise (<anonymous>)
    at eval (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:419:12)
From Your Spec Code:
    at setCookie (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:324:13)
    at _callee$ (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:60:20)
    at tryCatch (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:40090:40)
    at Generator.invoke [as _invoke] (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:40319:22)
    at Generator.prototype.<computed> [as next] (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:40142:21)
    at asyncGeneratorStep (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:401:24)
    at _next (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:423:9)
    at eval (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:430:7)
at new Promise (<anonymous>)
    at eval (http://localhost:61640/__cypress/tests?p=cypress/integration/genericError.feature:419:12)]]></failure>
    </testcase>
  </testsuite>
</testsuites>